import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar/page";
import NSK from "./NSK/page";
import About from "./About/page";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Form } from "react-hook-form";
import Inpform from "./Inpform/page";
import {User_profile} from "./user_profile/page"
import Link from "next/link";
import Home from "./Home/page";

var login = false
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "NSK - Nirudyoga Seva Kendhra",
  description: "Generated by create next app",
  icons: {
    icon: "/NSK-logo.png",
  },
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        
        <div className="flex flex-row gap-4 bg-white border-2 text-400  justify-between ">
            <NSK></NSK>
            <div className="flex flex-row position-relative">
                  <Link href="/Home"><Navbar name="Home" /></Link>
                  <Link href={!login ? "/Inpform" : "/User_profile"}><Navbar name="User Profile" /></Link>
                  <Link href={"/About"}><Navbar name="About"></Navbar></Link>
                  <Navbar name="Contact"></Navbar>
            </div>
            <div >
                {login ? (
              <Link href={"/signin"}><Button className="m-2">Sign Out</Button></Link>
            ) : (
              <>
                <Link href="/signin"><Button className="m-2">Sign In</Button></Link>
                <Link href="/Inpform"><Button className="m-2">Sign Up</Button></Link>
              </>
            )}
            </div>
        </div>
        {children}
        
      </body>
    </html>
  );
}
